force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Set__c.field-meta.xml
<CustomField>
    <fullName>Set__c</fullName>
    <label>Set</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Triple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionCreator.cls
@RestResource(urlMapping='/Question/*')
global with sharing class QuestionCreator {

    @HttpPost
    global static String createQuestions(String requestStructure){
        try {
            List<CreateQuestionWrapper> questionsList = (List<CreateQuestionWrapper>) JSON.deserialize(requestStructure, List<CreateQuestionWrapper>.class);
            List<Question__c> questions = new List<Question__c>();
            Map<String, CreateQuestionWrapper> textVsWrapperMap = new Map<String, CreateQuestionWrapper>();
            for(CreateQuestionWrapper wrapper : questionsList) {
                Question__c question = new Question__c();
                question.Text__c = wrapper.text;
                question.Type__c = wrapper.type;
                question.Set__c = wrapper.questionSet;
                questions.add(question);
                textVsWrapperMap.put(wrapper.text, wrapper);
            }
            insert questions;
            List<Option__c> options = new List<Option__c>();
            for(Question__c question : questions) {
                CreateQuestionWrapper wrapper = textVsWrapperMap.get(question.Text__c);
                for(CreateQuestionWrapper.OptionWrapper optWrapper : wrapper.options) {
                    Option__c option = new Option__c();
                    option.Text__c = optWrapper.text;
                    option.Correct__c = optWrapper.correct;
                    option.Question__c = question.Id;
                    options.add(option);
                }
            }
            insert options;
            return 'All records inserted successfully';
        } catch (Exception e) {
            throw new InvalidDataException(e.getMessage() + ' stack ' + e.getStackTraceString());
        }
    }

    public class InvalidDataException extends Exception {}
}