force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Set__c.field-meta.xml
<CustomField>
    <fullName>Set__c</fullName>
    <label>Set</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Triple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Quiz_CC.cls
public with sharing class Quiz_CC {

    @AuraEnabled
    public static List<QuestionResponseWrapper> getQuestions(Map<String, String> kvData){
        try {
            if(kvData == null) {
                throw new InvalidDataException('failed to provide parameters');
            }
            if(!kvData.containsKey('sequence')) {
                kvData.put('sequence', 'false');
            }
            String paperSet = kvData.get('paperSet');
            Boolean sequence = Boolean.valueOf(kvData.get('sequence'));
            String exam = kvData.get('exam');
        
            String query = 'SELECT Id, Text__c, Type__c, (SELECT Id, Text__c, Correct__c FROM Options__r) FROM Question__c';
            if(paperSet != null)
                query += ' WHERE Set__c = :paperSet';
            if(exam != null)
                query += ' AND Exam__c = :exam';
            if(sequence)
                query += ' ORDER BY CreatedDate ASC';
            query += ' LIMIT 60';
            List<Question__c> queriedQuestions = Database.query(query);
            List<QuestionResponseWrapper> questionResponseWrapperList = new List<QuestionResponseWrapper>();
            Integer index = 1;
            for(Question__c queriedQuestion : queriedQuestions) {
                questionResponseWrapperList.add(new QuestionResponseWrapper(queriedQuestion, index++)); 
            }
            return questionResponseWrapperList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    
    @AuraEnabled
    public static List<ExamWrapper> getSetsAndExams() {
        Map<String, Set<String>> examVsSetsMap = new Map<String, Set<String>>();
        List<Question__c> questions = [SELECT Id, Exam__c, Set__c FROM Question__c];
        for(Question__c question : questions) {
            if(examVsSetsMap.containsKey(question.Exam__c)) {
                examVsSetsMap.get(question.Exam__c).add(question.Set__c);
            } else {
                examVsSetsMap.put(question.Exam__c, new Set<String> { question.Set__c });
            }
        }
        List<ExamWrapper> exams = new List<ExamWrapper>(); 
        for(String exam : examVsSetsMap.keySet()) {
            exams.add(new ExamWrapper(
                exam,
                examVsSetsMap.get(exam)
            ));
        }
        return exams;
    }
    
    public class InvalidDataException extends Exception {}
}