force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Triple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionResponseWrapper.cls
public with sharing class QuestionResponseWrapper {
    @AuraEnabled public String id;
    @AuraEnabled public String text;
    @AuraEnabled public String type;
    @AuraEnabled public Integer index;
    @AuraEnabled public String selectedOptionId = ''; //for single choice
    @AuraEnabled public List<String> selectedOptionsIds = new List<String>(); //for multiple choice
    @AuraEnabled public List<OptionWrapper> correctOptions = new List<OptionWrapper>();
    @AuraEnabled public List<OptionWrapper> incorrectOptions = new List<OptionWrapper>();

    private class OptionWrapper {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
        @AuraEnabled public Boolean correct;
    }

    public QuestionResponseWrapper(Question__c question, Integer index) {
        this.id = question.Id;
        this.text = question.Text__c;
        this.type = question.Type__c;
        this.index = index;
        for(Option__c option : question.Options__r) {
            OptionWrapper optionWrapper = new OptionWrapper();
            optionWrapper.value = option.Id;
            optionWrapper.label = option.Text__c;
            optionWrapper.correct = option.Correct__c;
            if(option.Correct__c)
                correctOptions.add(optionWrapper);
            else
                incorrectOptions.add(optionWrapper);
        }
    }
}